apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: controller-approve
rules:
  - apiGroups:
      - cert-manager.io
    resources:
      - signers
    verbs:
      - approve
    resourceNames:
      - issuers.certmanager.freeipa.org/*
      - clusterissuers.certmanager.freeipa.org/*
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: controller-approve
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: controller-approve
subjects:
  - kind: ServiceAccount
    name: cert-manager
    namespace: cert-manager
