apiVersion: certmanager.freeipa.org/v1beta1
kind: ClusterIssuer
metadata:
  labels:
    app.kubernetes.io/name: clusterissuer
    app.kubernetes.io/instance: clusterissuer-sample
    app.kubernetes.io/part-of: freeipa-issuer
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: freeipa-issuer
  name: clusterissuer-sample
spec:
  # TODO(user): Add fields here
